### ISSUE TITLE
IllegalStateException: Could not resolve spoon dependencies

### ISSUE THREAD

**Issue by niqo01** [stanfy/spoon-gradle-plugin#1]
Hello,

I am trying your plugin but I get the following error:

```
java.lang.IllegalStateException: Could not resolve spoon dependencies
	at com.stanfy.spoon.gradle.SpoonRunTask.getClasspath(SpoonRunTask.groovy:111)
	at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:73)
	at org.gradle.util.JavaMethod.invoke(JavaMethod.java:62)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:527)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:510)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 52 more

```

Below my config:

    compileSdkVersion 18
    buildToolsVersion "18.1"

    Gradle 1.8
    gradle android plugin 0.6.1

**Comment by l070020** [comment]
@mkuprionis thanks for solution
