### ISSUE TITLE
Error while starting tests on multiple devices

### ISSUE THREAD

**Issue by FisherKK** [stanfy/spoon-gradle-plugin#128]
Hello,

I am encountering following problem when I try to use spoon in order to run tests on more than 1 device:

```
[09:41:26]: ▸ 2016-09-15 09:41:26 [SR.runTests] Executing instrumentation suite on 2 device(s).
[09:41:26]: ▸ 2016-09-15 09:41:26 [SR.runTests] Application: com.my-app.debug1 from /Users/F1sherKK/Dev/MyApp-Android/app/build/outputs/apk/app-automation-integrationTest.apk
[09:41:26]: ▸ 2016-09-15 09:41:26 [SR.runTests] Instrumentation: com.my-app.debug1.test from /Users/F1sherKK/Dev/MyApp-Android/app/build/outputs/apk/app-automation-integrationTest-androidTest.apk
[09:41:26]: ▸ 2016-09-15 09:41:26 [SR.runTests] [emulator-5556] Starting execution.
[09:41:26]: ▸ 2016-09-15 09:41:26 [SR.runTests] [05f3785c3444f1bf] Starting execution.
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.runInNewProcess] [05f3785c3444f1bf]
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.runInNewProcess] [emulator-5556]
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR Error: A JNI error has occurred, please check your installation and try again
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR Exception in thread "main" java.lang.NoClassDefFoundError: com/android/ddmlib/InstallException
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at java.lang.Class.getDeclaredMethods0(Native Method)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at java.lang.Class.getMethod0(Class.java:3018)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at java.lang.Class.getMethod(Class.java:1784)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR Caused by: java.lang.ClassNotFoundException: com.android.ddmlib.InstallException
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:41:26]: ▸ 2016-09-15 09:41:26 [SDR.printStream] [emulator-5556] STDERR 	... 7 more
```

Error occurs on any kind of devices. For example 2 smarphones, 2 emulators, 1 emulator 1 smartphone. It works with one device only.

I don't know what can I add to help to identify a problem. 

Gradle:
` classpath 'com.android.tools.build:gradle:2.2.0-rc2'`

Gradle-Wrapper:
`distributionUrl=https\://services.gradle.org/distributions/gradle-3.0-all.zip`

Spoon-gradle-plugin:
`
classpath('com.stanfy.spoon:spoon-gradle-plugin:1.2.2') {
            exclude module: "guava"
        }
        classpath 'com.google.guava:guava:18.0
`

Spoon-client:
`
com.squareup.spoon:spoon-client:1.6.4
`

Build tools ver:
24.0.0

Java ver:
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

And I assume that problem might be on my side because example project is able to run on two devices. I failed to update it to the same build-tools/gradle version as my project though. After updating gradle then gradle-wrapper-plugin in root location of Spoon-Gradle-Plugin project throws error that it uses gradle-2.12 and 2.14 is minimum. After I updated it then I get another errors from groovy.

I would be grateful if you could help me to identify where is the problem.

**Comment by roman-mazur** [comment]
It should be related to either Android gradle plugin version or build tools version in use.
Try downgrading them on your project to what example in this repo uses.
I would do downgrades separately for gradle plugin and build tools to check what causes the issue.

**Comment by FisherKK** [comment]
Thanks for fast response. I will give it a try and report back.

**Comment by FisherKK** [comment]
You were right. Issue was my gradle-wrapper version - 3.0, after I changed it to 2.14.1 then it started to work.

**Comment by roman-mazur** [comment]
hm, it's interesting... I actually did not expect the Gradle version will be the cause.

You might also try running with Gradle 3 without the daemon (if I remember correctly, it's enabled by default in 3.0 - `--no-daemon` command line option).
