### ISSUE TITLE
No such property: sdkDirectory for class: com.android.build.gradle.AppPlugin

### ISSUE THREAD

**Issue by chris-horner** [stanfy/spoon-gradle-plugin#24]
Just updated to 0.10.0 of the build tools, and now `./gradlew spoon` fails with "No such property: sdkDirectory for class: com.android.build.gradle.AppPlugin"

Stacktrace...

```
Caused by: groovy.lang.MissingPropertyException: No such property: sdkDirectory for class: com.android.build.gradle.AppPlugin
at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:110)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:219)
at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:212)
at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:201)
at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:533)
at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:516)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

**Comment by mariusbob** [comment]
Hi there,
I have just encountered the issue again when running `./gradlew spoon`
