### ISSUE TITLE
plugin breaks lint on new versions of android plugin

### ISSUE THREAD

**Issue by andaag** [stanfy/spoon-gradle-plugin#33]
Hi

See this thread : https://groups.google.com/forum/#!topic/adt-dev/ezM6RmO_ADY

We tracked it down to this plugin. If we remove that lint works fine.

**Comment by pvegh** [comment]
When using the workaround above (which fixes the lint issue), Spoon does not work anymore with multiple devices are attached. One device still works though.
Here is a some output:

2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.lang.Class.getDeclaredMethods0(Native Method)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.lang.Class.getDeclaredMethods0(Native Method)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.lang.Class.getMethod0(Class.java:3010)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.lang.Class.getMethod0(Class.java:3010)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.lang.Class.getMethod(Class.java:1776)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.lang.Class.getMethod(Class.java:1776)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.security.AccessController.doPrivileged(Native Method)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.security.AccessController.doPrivileged(Native Method)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR 	... 7 more
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR 	... 7 more
