### ISSUE TITLE
When using the workaround for the Lint issue, Spoon does not run with multiple devices anymore

### ISSUE THREAD

**Issue by pvegh** [stanfy/spoon-gradle-plugin#36]
When using the workaround fixes the lint issue (described on the main page of spoon-gradle-plugin), Spoon does not work anymore with multiple devices are attached. One device still works though.

This output is from a run of 2 tests on 2 devices:
```
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.lang.Class.getDeclaredMethods0(Native Method)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.lang.Class.getDeclaredMethods0(Native Method)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.lang.Class.getMethod0(Class.java:3010)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.lang.Class.getMethod0(Class.java:3010)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.lang.Class.getMethod(Class.java:1776)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.lang.Class.getMethod(Class.java:1776)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.security.AccessController.doPrivileged(Native Method)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.security.AccessController.doPrivileged(Native Method)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-01-20 17:21:16 [SDR.printStream] [4df1cb5a5ef88fa7] STDERR ... 7 more
2015-01-20 17:21:16 [SDR.printStream] [034b2915093ab9bf] STDERR ... 7 more
```

**Comment by roman-mazur** [comment]
We have to find a cause for `ClassNotFoundException: com.google.common.collect.Multimap`. Running gradle with `-d` option together with analyzing `logcat` output should help.

**Comment by pvegh** [comment]
Neither debug nor stacktrace seem to deliver any more information that is actually useful. Temporarily solved the problem by removing the guava workaround and splitting up the usage of lint and spoon tasks. Probably needs more testing though.
