### ISSUE TITLE
Timeout getting device list.

### ISSUE THREAD

**Issue by rtruxler** [stanfy/spoon-gradle-plugin#71]
Running 
`./gradlew :MyProject:spoonDebug --stacktrace`
yields this crash on versions 1.0.0 and up:

```
Caused by: java.lang.RuntimeException: Timeout getting device list.
	at com.squareup.spoon.SpoonUtils.waitForAdb(SpoonUtils.java:144)
	at com.squareup.spoon.SpoonUtils.initAdb(SpoonUtils.java:104)
	at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:98)
	at com.squareup.spoon.SpoonRunner$run.call(Unknown Source)
	at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:141)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

On 0.14.1 I get this crash:
```
Caused by: java.lang.IllegalStateException: AndroidDebugBridge.init() has already been called.
	at com.android.ddmlib.AndroidDebugBridge.init(AndroidDebugBridge.java:202)
	at com.squareup.spoon.SpoonUtils.initAdb(SpoonUtils.java:100)
	at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:79)
	at com.squareup.spoon.SpoonRunner$run.call(Unknown Source)
	at com.stanfy.spoon.gradle.SpoonRunTask.runSpoon(SpoonRunTask.groovy:132)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:589)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:572)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
```

I'm currently using gradle 2.4, build tools 22.0.1

Any ideas?

I've tried adb kill-server and adb start-server but it does nothing. Also, I can run adb commands just fine, including adb shell and adb devices.

Thanks, Rob

**Comment by rtruxler** [comment]
Update: It looks like I'm getting the same result from running `./gradlew :MyProject:connectedAndroidTest` so this must not be a spoon issue

**Comment by roman-mazur** [comment]
The latest plugin version is 1.0.3. You might try it as well.

**Comment by rtruxler** [comment]
Turns out the gradle daemon(s) were in a funky state. I was surprised that simply restarting adb didn't help, but running `./gradlew --stop` fixed it.

I can now use gradle version 2.4, spoon gradle plugin 1.0.3, spoon 1.1.9

**Comment by ObjectiveTruth** [comment]
If anyone comes across this. It was solved for me by increasing the adbTimeout in `build.gradle`. Apparently my CI server wasn't fast enough :+1: 

```
spoon {
    adbTimeout = 60 * 3
}
```
