### ISSUE TITLE
java.lang.StackOverflowError when using trello/victor

### ISSUE THREAD

**Issue by RomainPiel** [stanfy/spoon-gradle-plugin#72]
I just added trello/victor to my project and for some reason spoon-gradle-plugin is failing on a StackOverflowError:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:spoonProductionDebugAndroidTest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.StackOverflowError
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure6.doCall(SpoonRunTask.groovy:209)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:208)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
	at com.stanfy.spoon.gradle.SpoonRunTask$_checkDependencies_closure7.doCall(SpoonRunTask.groovy:215)
	at com.stanfy.spoon.gradle.SpoonRunTask.checkDependencies(SpoonRunTask.groovy:214)
```

I suspect that Victor has a cyclic dependency somewhere but I don't think that the plugin should fail on that. Any idea?

**Comment by roman-mazur** [comment]
Yes, it's definitely a bug.
[`checkDependencies` method](https://github.com/stanfy/spoon-gradle-plugin/blob/master/src/main/groovy/com/stanfy/spoon/gradle/SpoonRunTask.groovy#L217) should keep track on what dependencies have already been visited and skip them.

**Comment by RomainPiel** [comment]
Why do you need to collect all the dependencies? I see that you're using them to build the classpath, why not using `project.buildscript.configurations.classpath.asPath`?

**Comment by roman-mazur** [comment]
The original idea was to be selective and use only spoon runner and its dependencies for the classpath. I believe adding everything should also work.

**Comment by RomainPiel** [comment]
That's what https://github.com/x2on/gradle-spoon-plugin is doing. I'm not sure what could it impact though. I guess we should have a play with it :)
