### ISSUE TITLE
Spoon gradle with Cucumber

### ISSUE THREAD

**Issue by rafaelaazevedo** [stanfy/spoon-gradle-plugin#75]
I am using Cucumber with Robotium and I am trying to use Spoon for the reports, but I am having this message: 

java.lang.IllegalArgumentException: Could not find test class!
at com.squareup.spoon.Spoon.findTestClassTraceElement(Spoon.java:171)
at com.squareup.spoon.Spoon.screenshot(Spoon.java:50)
at com.betomorrow.tmn.apploader.test.LoginSteps.setup(LoginSteps.java:33)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at cucumber.runtime.Utils$1.call(Utils.java:37)
at cucumber.runtime.Timeout.timeout(Timeout.java:13)
at cucumber.runtime.Utils.invoke(Utils.java:31)
at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:59)
at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:222)
at cucumber.runtime.Runtime.runHooks(Runtime.java:210)
at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:200)
at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:163)
at cucumber.runtime.android.CucumberExecutor.execute(CucumberExecutor.java:110)
at cucumber.api.android.CucumberInstrumentationCore.start(CucumberInstrumentationCore.java:88)
at cucumber.api.android.CucumberInstrumentation.onStart(CucumberInstrumentation.java:26)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)

It seems that Spoon is not working with CucumberRunner. My runner class is:
public class Instrumentation extends CucumberInstrumentation {
         }

I could not find many support about spoon and cucumber on the internet, I know that spoon supports Cucumber, but it is not clear if I need to change anything on the runner class or on my steps class.

**Comment by roman-mazur** [comment]
`Spoon` class has 2 variants of `screenshot` method. The one used by you tries to resolve test class/method names using the stack trace. Spoon can do it for JUnit tests. In case of Cucumber, stacktrace is absolutely different and Spoon cannot guess the name of your test.
But you can use [another variant](https://github.com/square/spoon/blob/parent-1.2.0/spoon-client/src/main/java/com/squareup/spoon/Spoon.java#L70-L71) and provide test class/method name manually.

**Comment by rafaelaazevedo** [comment]
Many, many thanks !

**Comment by rafaelaazevedo** [comment]
Hi again, now it's taking the screenshots, but it's not showing in the report. I know that probably is the problem with the test class name and the method, but I tried so many things and didn't work:

I am trying this:         

Spoon.screenshot(mSolo.getCurrentActivity(), "initial_state", getClass().getCanonicalName(), "i_open_the_app"));

thank you !

**Comment by rafaelaazevedo** [comment]
I found the problem !!

Actually if I pass the method and the classname running with Cucumber won't work. I had to change the "Classname" for the Feature name and the "Method Name" for the Scenario name. thanks !

**Comment by roman-mazur** [comment]
:+1:
