### ISSUE TITLE
Problem with launching spoon on more than one device

### ISSUE THREAD

**Issue by FisherHUB** [stanfy/spoon-gradle-plugin#82]
Hello I've been using stanfy/spoon-gradle-plugin for a while. I was able to launch tests on 3-4 devices without a problems. As lately gradle and spoon-gradle-plugin dependencies/libs were updated I wanted to give it a try again. It works on one deivce. It crashes on two devices giving me this error:

```
2015-11-20 15:36:07 [SR.runTests] Executing instrumentation suite on 2 device(s).
2015-11-20 15:36:07 [SR.runTests] Application: com.myproject.debug1 from /Users/F1sherKK/Dev/MyProject/app/build/outputs/apk/app-debug.apk
2015-11-20 15:36:07 [SR.runTests] Instrumentation: com.myproject.debug1.test from /Users/F1sherKK/Dev/MyProject/app/build/outputs/apk/app-debug-androidTest-unaligned.apk
2015-11-20 15:36:07 [SR.runTests] [04ffe19ad317d2e7] Starting execution.
2015-11-20 15:36:07 [SR.runTests] [192.168.56.101:5555] Starting execution.
2015-11-20 15:36:07 [SDR.runInNewProcess] [04ffe19ad317d2e7]
2015-11-20 15:36:07 [SDR.runInNewProcess] [192.168.56.101:5555]
2015-11-20 15:36:07 [SDR.printStream] [04ffe19ad317d2e7] STDOUT 2015-11-20 15:36:07 [SDR.main] ERROR: Unable to execute test for target.  Exception message: Timeout getting device list.
2015-11-20 15:36:07 [SDR.printStream] [192.168.56.101:5555] STDOUT 2015-11-20 15:36:07 [SDR.main] ERROR: Unable to execute test for target.  Exception message: Timeout getting device list.
2015-11-20 15:36:07 [SDR.printStream] [04ffe19ad317d2e7] STDOUT java.lang.RuntimeException: Timeout getting device list.
2015-11-20 15:36:07 [SDR.printStream] [192.168.56.101:5555] STDOUT java.lang.RuntimeException: Timeout getting device list.
2015-11-20 15:36:07 [SDR.printStream] [04ffe19ad317d2e7] STDOUT 	at com.squareup.spoon.SpoonUtils.waitForAdb(SpoonUtils.java:143)
2015-11-20 15:36:07 [SDR.printStream] [192.168.56.101:5555] STDOUT 	at com.squareup.spoon.SpoonUtils.waitForAdb(SpoonUtils.java:143)
2015-11-20 15:36:07 [SDR.printStream] [04ffe19ad317d2e7] STDOUT 	at com.squareup.spoon.SpoonUtils.initAdb(SpoonUtils.java:104)
2015-11-20 15:36:07 [SDR.printStream] [192.168.56.101:5555] STDOUT 	at com.squareup.spoon.SpoonUtils.initAdb(SpoonUtils.java:104)
2015-11-20 15:36:07 [SDR.printStream] [04ffe19ad317d2e7] STDOUT 	at com.squareup.spoon.SpoonDeviceRunner.main(SpoonDeviceRunner.java:434)
2015-11-20 15:36:07 [SDR.printStream] [192.168.56.101:5555] STDOUT 	at com.squareup.spoon.SpoonDeviceRunner.main(SpoonDeviceRunner.java:434)
2015-11-20 15:36:07 [SDR.runInNewProcess] Process.waitFor() finished for [192.168.56.101:5555] with exitCode 1
2015-11-20 15:36:07 [SDR.runInNewProcess] Process.waitFor() finished for [04ffe19ad317d2e7] with exitCode 1
java.io.FileNotFoundException: /Users/F1sherKK/Dev/MyProject/app/build/spoon-log/debug/work/192_168_56_101_5555/result.json (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.squareup.spoon.SpoonDeviceRunner.runInNewProcess(SpoonDeviceRunner.java:140)
	at com.squareup.spoon.SpoonRunner$1.run(SpoonRunner.java:171)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
java.io.FileNotFoundException: /Users/F1sherKK/Dev/MyProject/app/build/spoon-log/debug/work/04ffe19ad317d2e7/result.json (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.squareup.spoon.SpoonDeviceRunner.runInNewProcess(SpoonDeviceRunner.java:140)
	at com.squareup.spoon.SpoonRunner$1.run(SpoonRunner.java:171)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-11-20 15:36:07 [SR$1.run] [04ffe19ad317d2e7] Execution done. (0 remaining [])
2015-11-20 15:36:07 [SR$1.run] [192.168.56.101:5555] Execution done. (0 remaining [])
:app:spoonDebugAndroidTest FAILED
```

My current config looks like that:

- gradle root:
```
dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'com.squareup.spoon:spoon-runner:1.2.1'
        classpath ('com.stanfy.spoon:spoon-gradle-plugin:1.0.4-SNAPSHOT') {
            exclude module: "guava"
        }
        classpath 'com.google.guava:guava:18.0'
    }
}
```

- gradle in app module:
```
apply plugin: 'spoon'

android {
    defaultConfig {
        testInstrumentationRunner "com.myproject.instrumentation.helper.runner.MyTestRunner"
    }

    testBuildType 'debug'
}

dependencies {

    androidTestCompile 'junit:junit:4.12'
    androidTestCompile 'com.squareup.spoon:spoon-client:1.2.1'
    androidTestCompile 'com.jraska:falcon-spoon-compat:0.3.1'
    androidTestCompile 'com.android.support:support-annotations:23.1.1'

    androidTestCompile 'com.android.support.test:runner:0.4.1'
    androidTestCompile 'com.android.support.test:rules:0.4.1'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.1'
    androidTestCompile 'com.android.support.test.espresso:espresso-web:2.2.1'

    androidTestCompile "org.mockito:mockito-core:1.10.19"
    androidTestCompile "com.google.dexmaker:dexmaker:1.2"
    androidTestCompile "com.google.dexmaker:dexmaker-mockito:1.2"
}

spoon {
    debug = true
    baseOutputDir = file("$buildDir/spoon-log")
    if (project.hasProperty('spoonClassName')) {
        className = project.spoonClassName

        if (project.hasProperty('spoonMethodName')) {
            methodName = project.spoonMethodName
        }
    }
}
```

I run tests by:
```
./gradlew spoon
```

Anyone faced this problem before and might have idea how to fix it?

**Comment by roman-mazur** [comment]
This seems to be an ADB issue...
Can you successfully list connected devices with `adb devices`?

**Comment by FisherHUB** [comment]
Yes I am.

```
Kamils-MacBook-Pro:~ F1sherKK$ ./Library/Android/sdk/platform-tools/adb devices
List of devices attached
05f3785c3444f1bf	device
04ffe19ad317d2e7	device
```

**Comment by roman-mazur** [comment]
However, it looks like you are also using an emulator (serial
192.168.56.101:5555)

**Comment by FisherHUB** [comment]
I tried without and I have same error. In general I tried few things. I've downloaded your example project which is currently on 1.2.2 gradle and ran it on two devices. It worked. 

Then I've updated gradle to 1.5.0.
```
buildscript {
  repositories {
    mavenCentral()
    mavenLocal()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:1.5.0'
    classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.4-SNAPSHOT'
  }
```
 It didn't work for 2 devices, either for one because known error appeared:
```
com.android.ddmlib.IDevice.installPackage(Ljava/lang/String;Z[Ljava/lang/String;)Ljava/lang/String;
```

So I added spoon-runner to fix the error:
```
buildscript {
  repositories {
    mavenCentral()
    mavenLocal()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:1.5.0'
    classpath 'com.squareup.spoon:spoon-runner:1.2.1'
    classpath 'com.stanfy.spoon:spoon-gradle-plugin:1.0.4-SNAPSHOT'
  }
}
```
And received this for error for 1 device and for 2 devices. I used adb-kill and adb-devices returned only 1 device connected. I restarted pc and made sure there is no Genymotion running.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:spoonFreeDebugAndroidTest'.
> Timeout getting device list.
```

**Comment by Burbaka** [comment]
To resolve `Timeout getting device list.` try increase adb timeout in *spoon* scope of gradle.properties

```java
spoon {
  adbTimeout = 60 // 60 seconds
}
```

**Comment by FisherHUB** [comment]
Amazing. That works. Thank you very much.

**Comment by gioPucela** [comment]
for me adding adbTimeout doesn't work, no matter the value I set

**Comment by Burbaka** [comment]
@gioPucela are you using emulator or real device for testing (maybe a couple of devices connected)? I know that's sounds strange but try not to use USD 3.0 ports when connecting real devices.
